name: CI for Go and React TypeScript Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Go
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.0 # Adjust to your Go version

    # Install and test Go backend
    - name: Install dependencies for Go
      working-directory: ./backend # Adjust to your React frontend directory
      run: go mod tidy

    - name: Test Go backend
      working-directory: ./backend # Adjust to your React frontend directory
      run: go test ./tests

    # Set up Node.js for React
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20 # Adjust to your Node.js version
        
    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash
      
    # Install dependencies for React  
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: ~/.bun/bin/bun install

    # Format the front end code
    - name: Format using biome
      working-directory: ./frontend
      run: ~/.bun/bin/bunx biome format --write ./src

    # Build React frontend
    - name: Build React frontend
      working-directory: ./frontend
      run: ~/.bun/bin/bunx vite build
      
    # Uncomment once we have some front end tests
    # - name: Test React frontend
    #   working-directory: ./frontend
    #   run: npm test
